#!/bin/sh
t=/tmp/png2winicon.$$
pngtopnm "$1" > $t.pnm
#pngtopnm -alpha "$1" | pgmtopbm -threshold | convert -negate pbm:- pbm:$t.pbm
pngtopnm -alpha "$1" | pgmtopbm -threshold > $t.pbm
pnmcomp -alpha=$t.pbm $t.pnm $t.pbm $t.2.pnm
ppmtowinicon -andppms $t.2.pnm $t.pbm > "$2" 
rm $t.pnm $t.pbm $t.2.pnm
