#!/bin/sh

VER=`sed 's/^AM_INIT_AUTOMAKE(.*, * \([0-9][0-9\.]*\)).*/\1/p;d' configure.in`
REL=`sed 's/^RELEASE *= *\([0-9][0-9]*\).*/\1/p;d' configure.in`

VRR=$VER-$REL
VRD=$VER
VRP=$VER

FILES="survex-$VRR.src.rpm\
 survex_${VRD}_i386.deb survex-aven_${VRD}_i386.deb survex-svxedit_${VRD}_all.deb\
 survex-$VER.tar.gz survex-dos-$VER.exe survex-win32-$VER.exe\
 svxdoc-doswin-$VER.exe svxdoc-riscos-$VER.zip"

for a in survex-riscos-$VER.zip survex-dos286-$VER.exe; do
   if test -f $a ; then
      FILES="$FILES $a"
   fi
done

WEBDIR="software/$VRP"
HOST="tartarus.org"
DIR="/usr/data/www/survex.com/$WEBDIR"
ssh tartarus.org mkdir "$DIR"
scp $FILES "$HOST:$DIR"

DIR="/usr/data/www/survex.com/docs"
ssh tartarus.org mkdir "$HOST:$DIR.tmp"
scp -a doc/manual{,.{sgml,ps,txt,rtf}} "$HOST:$DIR.tmp"
ssh tartarus.org mv "$DIR" "$DIR.old" && ssh tartarus.org mv "$DIR.tmp" "$DIR"
ssh tartarus.org rm -rf "$RAW.old"
