#!/bin/sh

VER=`sed 's/^AM_INIT_AUTOMAKE(.*, * \([0-9][0-9\.]*\)).*/\1/p;d' configure.in`
REL=`sed 's/^RELEASE *= *\([0-9][0-9]*\).*/\1/p;d' configure.in`

VRR=$VER-$REL
VRD=$VER-1
VRP=$VER

FILES="survex-$VRR.src.rpm\
 survex-$VER.tar.gz survex-win32-$VER.exe\
 svxdoc-doswin-$VER.exe"
DEB_FILES="survex_$VRD.tar.gz survex_$VRD.dsc survex_${VRD}_i386.deb\
 survex_${VRD}_i386.changes survex-svxedit_${VRD}_all.deb"

WEBDIR="software/$VRP"
HOST="tartarus.org"
DIR="/usr/data/www/survex.com/$WEBDIR"
ssh tartarus.org mkdir "$DIR"
ssh tartarus.org mkdir "$DIR"/debian
scp $FILES "$HOST:$DIR"
scp $DEB_FILES "$HOST:$DIR"/debian

#DIR="/usr/data/www/survex.com/docs"
#ssh tartarus.org mkdir "$DIR.tmp"
#scp -C -pr doc/manual{,.{sgml,ps,txt,rtf}} "$HOST:$DIR.tmp"
#ssh tartarus.org mv "$DIR" "$DIR.old" \&\& mv "$DIR.tmp" "$DIR"
#ssh tartarus.org rm -rf "$DIR.old"
