#!/usr/bin/perl -w

# converter for POV-Ray gradient files produced by The Gimp
my $prev = 1.0;
while (my $l = <>) {
   if ($l =~ /.*\[(\d\.\d+) color rgbt <(\d\.\d+), (\d\.\d+), (\d\.\d+).*/) {
       if ($prev != $1) {
           my $r = int($2 * 255);
           my $g = int($3 * 255);
           my $b = int($4 * 255);
           print "$1 $r $g $b\n";
       }
       $prev = $1;
   }
}

