#!/usr/bin/perl -w

# converter for POV-Ray gradient files produced by The Gimp
my $points = 13;
my $prev = -1.0;
my $interval = 1.0 / ($points-1);
my $next = 0.0;
my $pr = 0;
my $pg = 0;
my $pb = 0;
my $prevpos = 0.0;
while (my $l = <>) {
   if ($l =~ /.*\[(\d\.\d+) color rgbt <(\d\.\d+), (\d\.\d+), (\d\.\d+).*/) {
       if ($prev != $1) {
           my $r = int($2 * 255);
           my $g = int($3 * 255);
           my $b = int($4 * 255);
	   my $pos = $1;
           while ($pos >= $next) {
               if ($prev == -1.0) {
                   print "$r $g $b\n";
	       }
	       else {
                   my $dr = ($r - $pr) * ($pos - $next) / ($pos - $prevpos);
                   my $dg = ($g - $pg) * ($pos - $next) / ($pos - $prevpos);
                   my $db = ($b - $pb) * ($pos - $next) / ($pos - $prevpos);
		   my $newr = $r + int($dr);
		   my $newg = $g + int($dg);
		   my $newb = $b + int($db);
		   print "$newr $newg $newb\n";
	       }
	       $next += $interval;
	   }
	   $pr = $r;
	   $pg = $g;
	   $pb = $b;
	   $prevpos = $pos;
       }
       $prev = $1;
   }
}

