#! /bin/sh

rel=yes
if test x"$1" = x-t ; then
   rel=
   shift
fi
mk=${@-src rpm deb doc alien djgpp mingw}
if test x"$rel" = xyes ; then
   # Update debian changelog entry if necessary
   # If it does get updated, then the next check will fail...
   ./update-debcl.pl
   # Check everything is checked into CVS
   if ! cvs diff > /dev/null 2> /dev/null ; then
      echo There are changes not checked into CVS - please rectify
      exit 1
   fi
   # Update ChangeLog
   CVS2CL=./cvs2cl.pl
   if ! test -x $CVS2CL ; then
      CVS2CL=../cvs2cl/cvs2cl.pl
   fi
   if ! $CVS2CL 2> /dev/null ; then
      echo Failed to update ChangeLog from CVS
      exit 1
   fi
fi
if test -f Makefile ; then
   if ! make distclean ; then
      echo make distclean failed
      exit 1
   fi
fi
if test x"$rel" = xyes ; then
   rm -f config.guess.new config.sub.new
   perl -e '-M "config.guess" && -M "config.sub" && exit 1' &&\
      wget ftp://ftp.gnu.org/gnu/config/config.guess -O config.guess.new &&\
      wget ftp://ftp.gnu.org/gnu/config/config.sub -O config.sub.new &&\
      chmod 755 config.guess.new config.sub.new &&\
      mv config.guess.new config.guess && mv config.sub.new config.sub
fi
aclocal
autoheader
automake -a
autoconf
if ! ./configure ; then
   echo configure failed
   exit 1
fi
if test x"$rel" = xyes ; then
   if ! make distcheck ; then
      echo make distcheck failed
      exit 1
   fi
else
   if ! make dist ; then
      echo make dist failed
      exit 1
   fi
fi
if test x"$rel" = xyes && expr "$mk" : '.*\<rpm\>' || test x"$mk" = xrpm ; then
   if rpm --version > /dev/null 2> /dev/null ; then
      if ! make rpm ; then
         echo make rpm failed
         exit 1
       fi
   else
       echo rpm not installed - skipping rpm generation
   fi
fi
if test x"$rel" = xyes && expr "$mk" : '.*\<deb\>' || test x"$mk" = xdeb ; then
   if ! make debian ; then
      echo make debian failed
      exit 1
   fi
fi
if test x"$rel" = xyes && expr "$mk" : '.*\<doc\>' || test x"$mk" = xdoc ; then
   if ! make dos_doc_exe ; then
      echo make dos_doc_exe failed
      exit 1
   fi
   if ! make riscos_doc_zip ; then
      echo make riscos_doc_zip failed
      exit 1
   fi
fi
if expr "$mk" : '.*\<alien\>'; then
   if ! make alien_src_zip ; then
      echo make alien_src_zip failed
      exit 1
   fi
fi
if ! make distclean ; then
   echo make distclean failed
   exit 1
fi
if expr "$mk" : '.*\<djgpp\>'; then
   SAVE_PATH="$PATH"
   # for building on mrs30
   if test -d /opt/crosstools/i386-pc-msdosdjgpp ; then
      PATH=/opt/crosstools/i386-pc-msdosdjgpp/bin:/opt/crosstools/bin:$PATH
   fi
   if ! ./configure --host=djgpp --with-x=no --disable-aven LDFLAGS=-s STRIP=echo CAVEROT=caverot.exe CRLIB=-lalleg CROBJX=dosrot.o ; then
      echo djgpp configure failed
      exit 1
   fi
   if ! make ; then
      echo djgpp make failed
      exit 1
   fi
   if ! make djgpp_exe ; then
      echo djgpp make djgpp_exe failed
      exit 1
   fi
   if ! make distclean ; then
      echo make distclean failed
      exit 1
   fi
   PATH="$SAVE_PATH"
fi
if expr "$mk" : '.*\<mingw\>'; then
   build_platform=`sh config.guess`
   SAVE_PATH="$PATH"
   if test -d /usr/local/cross-tools/i386-mingw32msvc/bin ; then
      # binaries from http://www.devolution.com/~slouken/SDL/Xmingw32/
      PATH=/usr/local/cross-tools/bin:/usr/local/cross-tools/i386-mingw32msvc/bin:$PATH
   else
      if test -d /usr/i586-mingw32msvc/bin ; then
         # debian mingw32 package
	 PATH=/usr/i586-mingw32msvc/bin:$PATH
	 CC=/usr/bin/i586-mingw32msvc-gcc
	 export CC
	 CXX=/usr/bin/i586-mingw32msvc-g++
	 export CXX
      else
	 # variant of debian mingw32 package?
	 PATH=/usr/i386-mingw32msvc/bin:$PATH
	 CC=/usr/bin/i386-mingw32msvc-gcc
	 export CC
	 CXX=/usr/bin/i386-mingw32msvc-g++
	 export CXX
      fi
   fi
   if ! ./configure --host=mingw32 --build=$build_platform --with-x=no WXCONFIG=`pwd`/mingw_extras/wxmsw-config LDFLAGS="-s -L/opt/rx-win32/lib" CPPFLAGS=-I/opt/rx-win32/include CAVEROT= ; then
      echo mingw configure failed
      exit 1
   fi
   if ! make ; then
      echo mingw make failed
      exit 1
   fi
   if ! make mingw_iss ; then
      echo mingw make mingw_iss failed
      exit 1
   fi
   if ! make distclean ; then
      echo make distclean failed
      exit 1
   fi
   PATH="$SAVE_PATH"
   CC=
   CXX=
fi
