#! /bin/sh
build=${@-riscos borlandc}
if ! ./configure ; then
   echo configure failed
   exit 1
fi
if expr "$build" : '.*\<riscos\>'; then
   if ! make riscos_zip ; then
      echo make riscos_zip failed
      exit 1
   fi
fi
if expr "$build" : '.*\<borlandc\>'; then
   if ! make borlandc_exe ; then
      echo make borlandc_exe failed
      exit 1
   fi
fi
