; pos=fail err=7 warn=5 dummycrprotection=

; Walls used to only check the day of the month was between 1 to 31
; (inclusive), but Walls v2.2.4 fixed this to be an error, and we've
; followed that lead.

; Were warnings, now errors:

; "30 days hath September"
#date 2003-09-31
; 2003 not a leap year
#date 2003-02-29
; 1900 not a leap year
#date 1900-02-29

; Survex can currently only represent dates between 1900 and 2078, so these
; should warn "Invalid year (< 1900 or > 2078)".
#date 1899-12-31
#date 2079-01-01
#date 12/31/1899
#date 01/01/2079
; 2100 not a leap year; we actually warn: "Invalid year (< 1900 or > 2078)"
#date 2100-02-29

; Valid:

; 2004 was a leap year
#date 2004-02-29
; 2000 was a leap year
#date 2000-02-29

; Errors:

; Month < 1
#date 2004-00-29
; Month > 12
#date 2004-13-29
; Day > 31
#date 2004-11-32
; Month and day both invalid
#date 2004-13-32

A B 1 2 3
