; pos=dump warn=3 dummycrprotection=
#u o=EUN v=g
#Fix U0 0 1 0
#seg foo
#date 2024-03-09 walls appears to ignore anything here
#Fix Q0 1 1 1
; Mammoth reportedly uses "0 0 0" legs between fixed points so we mustn't
; use INFER_EQUATES.
Q0 U0  0 0 0 ; Walls treats this like a NOSURVEY leg it seems
U0 U1  5.4 203 +50
#units v=d
#[
U1 X1 3 4 5
#[
X2 X3 7 24 25
X3 X4 9 14 15
#]
#date 1970-01-01
X1 X2 5 12 13
#]
#s bar
U1 *1,2,3,4*
#units feet decl=0.0 $foo_bar1="meters decl"
#date 1972/02/29
:U1 U2 10.1m N79E/S79W -28/24 *15 25 4 3*
#units $(foo_bar1)=-3 LRUD=F:UDLR
#Date 8/04/1973
U2 U3 33i1.6 N82E/-- -26/--- *15 25 4 3*
U3 <1 2 3 4>
U3 U4 30.14f /N90E /02 *1 2 3 2*
U4 U5 i11 -/N90E -/02 *1 2 3 2*
; odd apparently undocumented variants of a LRUD-only data line
U5 ZZ9 <1 2 3 4>
U5 U6 1 2/- 3/-
U6 ZZ8 *1 2 3 4*
#segment splays
U3 - 1.0 --- +90
U3 -- 1.0 ---- -90
#prefix test walls appears to ignore anything here
#units typeab=n,4,X
#units typeab=n,4,x
#units typeab=n,10
#units typevb=c,6,X
#units typevb=c,6,x
#units typevb=c,1
