; pos=dump warn=15 dummycrprotection=
#u o=EUN v=g
#Fix U0 0 1 0
#seg foo
#date 2024-03-09 walls appears to ignore anything here
#Fix Q0 1 1 1
; Mammoth reportedly uses "0 0 0" legs between fixed points so we mustn't
; use INFER_EQUATES.
Q0 U0  0 0 0 ; Walls treats this like a NOSURVEY leg it seems
#UNITS CASE=U
u0 u1  5.4 203d +45D
#units v=d case=none ; undocumented but unknown "case=" values -> "mixed"
#[
U1 X1 3 4 5
#[
X2 X3 7 24 25
X3 X4 9 14 15
#]
#date 1970-01-01
X1 X2 5 12 13
#]
#s bar
U1 *1,2,3,4*
#units feet decl=0.0 $foo_bar1="meters decl"
#date 1972/02/29
:U1 U2 10.1m N79E/S79W -28/24 *15 25 4 3*
#units $(foo_bar1)=-3 LRUD=F:UDLR
#Date 8/04/1973
U2 U3 33i1.6 N82E/-- -26/--- *15 25 4 3*
U3 <1 2 3 4>
U3 U4 30.14f /N90E /02 *1 2 3 2*
U4 U5 i11 -/N90E -/02 *1 2 3 2*
; odd apparently undocumented variants of a LRUD-only data line
U5 ZZ9 <1 2 3 4>
U5 U6 1 2/- 3/-
U6 ZZ8 *1 2 3 4*
; Regression test: `#` in a station name
U5 12#4 24.7 123.5 0 <0,0,0,0>
12#4 &##:S1 12.3 345.6 78 <0,0,0,0>
#segment splays
U3 - 1.0 --- +90
U3 -- 1.0 ---- -90
#units order=da
U3   --      7.8     098.7
#prefix test walls appears to ignore anything here
#prefix
#units typeab=n,4,X
#units typeab=n,4,x
#units typeab=n,10
#units typevb=c,6,X
#units typevb=c,6,x
#units typevb=c,1
#units inch=1 ; regression test
; Test no warning for values of unsupported options which are the default.
#units inch=0
; Walls seems to fail to check for junk after parsing a number in these cases:
#units uv=4gradeb) inch=1
#units uvv=4gradeb inch=1
#units uvh=4gradeb inch=1
#units typeab=n,4Q),X inch=1
#units typevb=c,1.2Q inch=1
; Test undocumented omission of clino
#units order=adv
U5  U7  123 1.00
#units order=dav
U7  U8  1.00 123
; Test explicit clino units (on plumb to check equivalent to 90°).
U8  U9  1.00 -- 90d
U9  U10 1.00 -- 100g
U10 U11 1.00 -- 1600m
#units $emptymacro;followed by a comment
U11 EMPTY: 1.00 -- 90
#units order=ENU rect
U0 U12a 30 40 50
#units rect=90
U0 U12b -40 30 50
