debian/tmp/usr/share/icons/hicolor/32x32/mimetypes/
debian/tmp/usr/share/icons/hicolor/scalable/mimetypes/
debian/tmp/usr/share/survex/bcra3.svx
debian/tmp/usr/share/survex/bcra5.svx
debian/tmp/usr/share/survex/*.msg
debian/tmp/usr/share/mime-info/survex.mime
debian/tmp/usr/share/mime-info/survex.keys
debian/tmp/usr/bin/3dtopos
debian/tmp/usr/bin/cad3d
debian/tmp/usr/bin/cavern
debian/tmp/usr/bin/diffpos
debian/tmp/usr/bin/dump3d
debian/tmp/usr/bin/extend
debian/tmp/usr/bin/sorterr
debian/tmp/usr/share/man/man1/3dtopos.1
debian/tmp/usr/share/man/man1/cad3d.1
debian/tmp/usr/share/man/man1/cavern.1
debian/tmp/usr/share/man/man1/diffpos.1
debian/tmp/usr/share/man/man1/extend.1
debian/tmp/usr/share/man/man1/sorterr.1
debian/tmp/usr/share/man/man7/survex.7
debian/tmp/usr/share/doc/survex
vim/ftdetect/survex.vim usr/share/vim/addons/ftdetect
vim/syntax/survex.vim usr/share/vim/addons/syntax
debian/vim-survex.yaml usr/share/vim/registry
