#!/bin/sh -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/survex -a -d /usr/share/doc/survex ]; then
		ln -sf ../share/doc/survex /usr/doc/survex
	fi
fi
# End automatically added section
# Automatically added by dh_installdocs
if command -v install-docs >/dev/null 2>&1; then
	install-docs -i /usr/share/doc-base/survex
fi
# End automatically added section
