#!/bin/sh -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/survex ]; then
	rm -f /usr/doc/survex
fi
# End automatically added section
# Automatically added by dh_installdocs
if command -v install-docs >/dev/null 2>&1; then
	install-docs -r survex
fi
# End automatically added section
