#!/bin/sh

prefix=/opt/wxmsw
exec_prefix=${prefix}
exec_prefix_set=no
CC="gcc"
CXX="c++"
LD="gcc -shared -o"

usage()
{
    cat <<EOF
Usage: wx-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version]
                 [--libs] [--cppflags] [--cflags] [--cxxflags]
                 [--cc] [--cxx] [--ld]

wx-config returns configuration information about the installed
version of wxWindows. It may be used to query its version and
installation directories and also retrieve the C and C++ compilers
and linker which were used for its building and the corresponding
flags.
EOF

    exit $1
}

cppflags()
{
    if test ${prefix}/include != /usr/include ; then
        if test ${prefix}/include != /usr/include/c++ ; then
            includes=-I${prefix}/include
        fi
    fi
    includes="$includes -I${exec_prefix}/lib/wx/include -D__USE_WXCONFIG__"
    echo $includes -D__WXMSW__ -fvtable-thunks -DWINVER=0x0400 -D__WIN95__ -D__GNUWIN32__ -DSTRICT -D__WINDOWS__ -D__WXDEBUG__ -fno-pcc-struct-return -fno-rtti -fno-exceptions
}

if test $# -eq 0; then
      usage 1 1>&2
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 2.2.7
      ;;
    --cppflags)
      cppflags
      ;;
    --cflags)
      echo `cppflags` 
      ;;
    --cxxflags)
      echo `cppflags`  
      ;;
    --libs)
      if test ${exec_prefix}/lib != /usr/lib ; then
        libs="-L${exec_prefix}/lib"
      fi
      echo -mwindows $libs -lwx -lpng -ljpeg -ltiff -lzlib -lxpm -lcomctl32 -lwsock32 -luuid -lole32 -lm
      ;;
    --cc)
      echo $CC
      ;;
    --cxx)
      echo $CXX
      ;;
    --ld)
      echo $LD
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

