name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push, or for pull requests against master
  push:
    paths-ignore:
      - NEWS
  pull_request:
    branches: [ master ]
    paths-ignore:
      - NEWS

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clang-sanitisers:
    runs-on: 'ubuntu-latest'
    container: debian:stable
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install package dependencies
      run: |
        apt-get update
        apt-get install -y \
            autoconf \
            automake \
            clang-16 \
            make \
            pkg-config \
            gettext \
            libwxgtk3.2-dev \
            libavcodec-dev \
            libavformat-dev \
            libproj-dev \
            libswscale-dev \
            mesa-common-dev \
            libglu1-mesa-dev \
            libx11-dev \
            libxext-dev \
            ghostscript \
            netpbm \
            x11proto-core-dev \
            liblocale-po-perl \
            unifont \
            docbook \
            docbook-utils \
            w3m
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
    - name: bootstrap source tree
      run: |
        ln INSTALL INSTALL-save
        autoreconf -fiv
        mv -f INSTALL-save INSTALL
    - name: configure
      run: |
        # We use clang here because (at least currently) it supports a few
        # extra sanitiser checks compared to GCC.
        export CC='ccache clang-16'
        export CXX='ccache clang++-16'
        # float-divide-by-zero, nullability and unsigned-overflow aren't
        # undefined behaviour checks, but they catch for things we don't expect
        # our code to do.
        export CFLAGS='-fsanitize=address,undefined,float-divide-by-zero,local-bounds,nullability,unsigned-integer-overflow -fsanitize-address-use-after-scope -fsanitize-recover=all -g -O2 -fno-omit-frame-pointer'
        export CXXFLAGS='-fsanitize=address,undefined,float-divide-by-zero,local-bounds,nullability,unsigned-integer-overflow -fsanitize-address-use-after-scope -fsanitize-recover=all -g -O2 -fno-omit-frame-pointer'
        ./configure
    - name: make
      run: make -j2
    - name: Run tests
      run: make check VERBOSE=1
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: |
        printf '%s\n' .ccache > ".git/info/exclude"
        git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
